/** Auto-generated by scripts/generate-stories.mjs */
import React from 'react';
import AuthContext from '../contexts/AuthContext';

// If this component does not have a default export, adjust to a named import
import Component from './PermissionGate';

export default {
  title: 'Components/PermissionGate',
  component: Component,
  tags: ['autodocs'],
  parameters: { layout: 'centered' },
  decorators: [
    (Story, context) => {
      // Very simple mock Auth context so PermissionGate can evaluate permissions
      const allow = context.args.mockAllow ?? true;
      const mockAuth = {
        hasPermission: () => allow,
        hasAnyPermission: () => allow,
        hasAllPermissions: () => allow,
      };
      return (
        <AuthContext.Provider value={mockAuth}>
          <Story />
        </AuthContext.Provider>
      );
    },
  ],
};

const Template = (args) => (
  <Component {...args}>{args.children}</Component>
);
export const Default = {
  render: Template,
  args: {
    permissions: 'access:dashboard',
    requireAll: false,
    children: (
      <div style={{ padding: 12, border: '1px solid #ddd', borderRadius: 6 }}>
        You have access. This content is visible.
      </div>
    ),
    fallback: (
      <div style={{ padding: 12, border: '1px dashed #f99', borderRadius: 6, color: '#a00' }}>
        No access. Showing fallback.
      </div>
    ),
    mockAllow: true,
  }
};

export const NoAccess = {
  render: Template,
  args: {
    ...Default.args,
    mockAllow: false,
  },
};
