import fg from 'fast-glob';
import fs from 'fs-extra';
import path from 'path';

// Scan for JS/JSX component files under src/components
const patterns = [
  'src/components/**/*.js',
  'src/components/**/*.jsx',
  '!**/*.stories.*',
  '!**/*.test.*',
  '!**/__tests__/**',
];

const files = await fg(patterns, { dot: false });
let created = 0;

for (const file of files) {
  const dir = path.dirname(file);
  const ext = path.extname(file); // .js | .jsx
  const base = path.basename(file, ext); // Component name
  const extNoDot = ext.replace(/^\./, '');
  const storyPath = path.join(dir, `${base}.stories.${extNoDot}`);

  if (await fs.pathExists(storyPath)) continue;

  // Derive a nice title like Components/Subdir/Component
  const relFromComponents = path.relative('src/components', dir);
  const titleSegments = ['Components', ...relFromComponents.split(path.sep).filter(Boolean), base];
  const title = titleSegments.join('/');

  const importPath = `./${base}`;

  const tpl = `/** Auto-generated by scripts/generate-stories.mjs */
import React from 'react';

// Import the component module and support both default and named exports
import * as ComponentModule from '${importPath}';
const Component = ComponentModule.default ?? ComponentModule[Object.keys(ComponentModule).find((k) => typeof ComponentModule[k] === 'function')] ?? (() => null);

export default {
  title: '${title}',
  component: Component,
  tags: ['autodocs'],
  parameters: { layout: 'centered' }
};

const Template = (args) => <Component {...args} />;
export const Default = {
  render: Template,
  args: {}
};
`;

  await fs.outputFile(storyPath, tpl, 'utf8');
  created++;
  console.log('Created', storyPath);
}

console.log(`Done. Created ${created} new stor${created === 1 ? 'y' : 'ies'}.`);
