/** Auto-generated by scripts/generate-stories.mjs */
import React from 'react';

// If this component does not have a default export, adjust to a named import
import Component from './EventFeedbackDashboard';

export default {
  title: 'Components/Events/EventFeedbackDashboard',
  component: Component,
  tags: ['autodocs'],
  parameters: { layout: 'centered' }
};

const Template = (args) => <Component {...args} />;
export const Default = {
  render: Template,
  args: {}
};
